# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Nasa Project CI

on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #checkout latest version of code from master branch
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3 #setup node environment
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run build --prefix client
