# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Nasa Project CI

on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    env:
      CI: true # disables watch mode and buffering of jest output
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #checkout latest version of code from master branch
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3 #setup node environment
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run build --prefix client
      - name: Run Tests
        run: npm run test
